version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db
    command: npm run dev

  backend-test:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: npm test
    profiles:
      - test

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: npm run dev

  frontend-test:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm test
    profiles:
      - test

  db:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    name: fullstack-music-app_default
